#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Sign-up route
app_signup:
    path: /signup
    controller: App\Controller\AuthController::signup

# Login routes
app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_logout:
    path: /logout
